name: Jarvis
options:
  bundleIdPrefix: com.jarvis
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  JarvisPackage:
    path: .

settings:
  base:
    SWIFT_VERSION: "5.9"
    ENABLE_USER_SCRIPT_SANDBOXING: false

targets:
  Jarvis-iOS:
    type: application
    platform: iOS
    sources:
      - path: Jarvis/iOS
      - path: Jarvis/Shared
    dependencies:
      - package: JarvisPackage
        product: JarvisShared
    settings:
      base:
        INFOPLIST_FILE: Jarvis/iOS/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.jarvis.ios
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

  Jarvis-macOS:
    type: application
    platform: macOS
    sources:
      - path: Jarvis/macOS
      - path: Jarvis/Shared
    dependencies:
      - package: JarvisPackage
        product: JarvisShared
    settings:
      base:
        INFOPLIST_FILE: Jarvis/macOS/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.jarvis.macos
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

  Jarvis-iOSTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: tests/iOS
    dependencies:
      - target: Jarvis-iOS
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.jarvis.ios.tests

  Jarvis-macOSTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: tests/macOS
    dependencies:
      - target: Jarvis-macOS
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.jarvis.macos.tests

schemes:
  Jarvis-iOS:
    build:
      targets:
        Jarvis-iOS: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - Jarvis-iOSTests

  Jarvis-macOS:
    build:
      targets:
        Jarvis-macOS: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - Jarvis-macOSTests
